version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8000:80"
    command: uvicorn news_aggregator.main:app --host 0.0.0.0 --port 80

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on: 
      - backend
    command: npm run dev -- --host